# Generated by Django 4.2.26 on 2025-11-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem_order_shop_order_created_cbf7b4_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
